[workspace]

resolver = "2"

members = [
  "pipes",
  "pipes-img",
  # "pipes-utils",
  "infinitask",
  # "pipes-infinity",
  "kravl-core",
  "pipes-fs",
  "pipes-http", "pipes-util", "pipes-quick", "pipes-package",
]
